# Generated by Django 5.1.6 on 2026-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_created_at_recipe_image_url_recipe_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="blog_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="season",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
