# Generated by Django 5.1.6 on 2026-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_blog_content_recipe_difficulty_recipe_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="keywords",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
