# Generated by Django 5.1.6 on 2026-03-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_ingredients_recipe_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cooking_methods",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="course",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cuisine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_keys",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
